### ISSUE TITLE
IE 11 support

### ISSUE THREAD

**Issue by jlnbreau** [johndatserakis/vue-navigation-bar#1]
could be great to have this compatibility support !

**Comment by johndatserakis** [comment]
Definitely - let me see what issues it's having with ie11 and how they can be fixed - will work on this soon.

**Comment by johndatserakis** [comment]
Hey there - so I'm pushing an update now that explains how to have this component work in older browsers. To summarize, you'll need to stick this at the bottom of your `index.html`

```html 
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.6.15/browser-polyfill.min.js"></script>
```

Or, you can install `babel-polyfill` and import that in the main script of your app. Then you'll be good to go. Thanks for bringing this up.

**Comment by johndatserakis** [comment]
Did this end up solving the issue for you? Let me know if I can help further, thanks.
