### ISSUE TITLE
Put a link in navigation bar to get bottom of page

### ISSUE THREAD

**Issue by kashyappiyush1998** [johndatserakis/vue-navigation-bar#15]
If I set path to "#contact" where id "contact" is in my footer at the bottom of the page. This doesn't work, just URL gets appended by "#contact"

**Comment by SomethingNew71** [comment]
@kashyappiyush1998 do you have any sort of vue-router in use? Perhaps that is preventing defualt anchor tags from working?

**Comment by kashyappiyush1998** [comment]
Yes I am using this navigation bar as an component, but I have a working router separately

**Comment by SomethingNew71** [comment]
Right I believe `vue-router` overwrites the default functionality for hashes so you need to manually manage anchor tag functionality on the pages if you use `vue-router`.

Possible solution: https://forum.vuejs.org/t/how-to-handle-anchors-bookmarks-with-vue-router/14563/7

**Comment by johndatserakis** [comment]
Hi there @ kashyappiyush1998, as @SomethingNew71 mentioned, `vue-router` needs some additional setup when looking to have anchors automatically scroll into view. I've run into this in the past myself.

I will add - you can achieve the desired effect without adding anything special to `vue-router`, by using the `vnb-item-clicked` emitted `event` offered by this library.

To do this, assign a menu item as a `isLinkAction: true`, and then put an event listen on your `vue-navigation-bar` usage: `<vue-navigation-bar :options="navbarOptions" @vnb-item-clicked="vnbItemClicked"/>`.

Then, in that method, as you filter for which item was clicked by checking the passed `text` parameter, you can just simply scroll to any `div` you'd like.

I went ahead and made a quick [codesandbox](https://codesandbox.io/s/vue-navigation-bar-scroll-example-8n3no?file=/src/App.vue) demonstrating this. Click on the `About` option in the menu options to scroll to the footer. Also, here's a `gif` of the codesandbox in action. Hopefully this can help with your issue:

![vnb-issue](https://user-images.githubusercontent.com/9972969/87843061-3abba800-c87f-11ea-9e66-633c5aec88a2.gif)
