### ISSUE TITLE
Possible height breakpoint?

### ISSUE THREAD

**Issue by jeffreykthomas** [johndatserakis/vue-navigation-bar#22]
Hi again, I just discovered an issue that if a user has a relatively small height for their browser (saw it on a friend's older laptop), and a sub-menu has several items in it (therefore it's height is greater than the screen height), the dropdown opens upwards (and is therefore not visible, since it opens up past the top of the screen). Is there a work-around for this?

**Comment by johndatserakis** [comment]
I see, thanks for calling that out. 

I'm a little bit booked at the moment, but if I get a block of time to get to this soon, I will. I'll let you know when it's complete.

As far as the actual issue, hmm yea it sounds strange. The library we use for the popups handles all that - I wonder if there's a way to force it to open in a certain direction in certain cases, like when the screen is shorter than a given height.

Is there anyway you could get a screenshot of this behavior? I'd like to maybe know how tall the screen was when it was having the issue.

**Comment by jeffreykthomas** [comment]
The issue appears in the demo too, if you reduce the height of your browser to less than the height of the about tab...

**Comment by johndatserakis** [comment]
Ok great, thanks for that. That's good that I can easily recreate it.

**Comment by jeffreykthomas** [comment]
Hi John, I looked further into this. I believe there is an option with the implementation of the tippy protocol that should prevent the issue. It's a feature of the Popper, to flip if there isn't space in the default direction. But that can be turned off.

I believe it would look like this:

```
tippy(el, {
        theme: "light",
        content: template,
        interactive: true,
        animation: this.options.tooltipAnimationType,
        role: "Menu",
        // trigger: 'click', // for testing
        trigger: "click mouseenter focus",
        appendTo: "parent",
        arrow: true,
        inertia: false,
        popperOptions: {
          modifiers: [
            {
              name: 'flip',
              options: {
                flipVariations: false,
              }
            }
          ]
        },
```

I would try it on my own, but I'm a newbie at all of this, so don't know the proper way to fork the project, etc...

Here are the two links from the documents of tippy and popper:
https://atomiks.github.io/tippyjs/v6/all-props/#placement
https://popper.js.org/docs/v2/modifiers/flip/#options

**Comment by johndatserakis** [comment]
No sweat - thanks for the further context. I will try to get to this in the next few days! Sorry for the wait.
