### ISSUE TITLE
Can i add text between link in submenuoptions?

### ISSUE THREAD

**Issue by satria1697** [johndatserakis/vue-navigation-bar#24]
I want to give text on submenuoptions

**Comment by johndatserakis** [comment]
Hi there - hmm no I don't think that's possible at the moment. To do that we'd need to update the hover of each item to not take over the whole item. Maybe allowing HTML in there would be a solution. To be honest, I think that may be out of scope for this project, as we want to make it as simple as possible to setup the navbar. You may want to check out something like https://bootstrap-vue.org/docs/components/navbar perhaps - that gives you more customization options.

**Comment by satria1697** [comment]
ah, kay kay, thanks~
