### ISSUE TITLE
Adding external links to a button

### ISSUE THREAD

**Issue by layrayson** [johndatserakis/vue-navigation-bar#27]
How do I make the button click visit an external website link

**Comment by raykudo** [comment]
https://github.com/johndatserakis/vue-navigation-bar#notes

> Sometimes you may want your links to perform an action instead of following a link. To do this, add the isLinkAction property to your menuOption and it'll emit the vnb-item-clicked event with the text property of the menuOption . This will suppress the path option so the link no longer goes anywhere, but instead just sends the event. Checkout the example page to see this in action.

example
```
<template>
  <vue-navigation-bar
    :options="navbarOptions" 
    @vnb-item-clicked="vnbItemClicked"
  />
</template>

<script>
...
data () {
  return {
    navbarOptions: {
      ....,
      menuOptionsLeft: [
        {
          type: "button",
          text: "External Link",
          isLinkAction: true
        }
      ]
    }
  }
},
methods: {
    vnbItemClicked(text) {
      if (text === "External Link") {
        window.open("put the link here")
      }
    }
  }
</script>
```
