### ISSUE TITLE
How to use v-if or v-show to display and hide submenu ?

### ISSUE THREAD

**Issue by whsasf** [johndatserakis/vue-navigation-bar#28]
How to use v-if or v-show to display and hide submenu ?

**Comment by johndatserakis** [comment]
Hi there - if I'm understanding your question correctly, I would say you would want to assign your options object as computed variable, and dynamically update the options object itself based on whatever you were trying to evaluate with the v-if or v-show.

**Comment by firstmeet** [comment]
When I use v-if or v-show,the submenu will display.How to hide the submenu

**Comment by johndatserakis** [comment]
Best way to hide and show things like the submenu is to update the options object to remove the submenu content, if I'm understanding your question correctly.
