### ISSUE TITLE
Change brand image size

### ISSUE THREAD

**Issue by AniaKru95** [johndatserakis/vue-navigation-bar#29]
Hi, 

I would like to know, is it possible to change brand image size?

            brandImagePath: "./",
            brandImage: require("../assets/example.svg"),
            brandImageAltText: "brand-image"

**Comment by johndatserakis** [comment]
Hi there, sure, you can add custom styling to do that.

```scss
.vnb {
  &__brand-image-wrapper {
    &__link {
      &__image {
		// Your custom styles here
      }
    }
  }
}
```
