### ISSUE TITLE
Allowing action for submenu

### ISSUE THREAD

**Issue by tonystaark** [johndatserakis/vue-navigation-bar#3]
@johndatserakis  Besides having the function to navigate to certain paths, would  you allow the submenu option to trigger action upon clicking? Maybe add an action field allowing function to trigger ?

**Comment by johndatserakis** [comment]
Hey there - yea I think something this will be a good addition to the library. 

How about when a menu or submenu option is clicked they will `$emit` an event that you can catch on your component and do whatever function you like. Does that sound like a good plan?

I will begin working on this soon and presume I'll have it done in about a week - sorry I'm just a bit swamped right now - thank you for the suggestion.

**Comment by johndatserakis** [comment]
Hey @tonystaark - so I just pushed v2.0.0. It has a bunch of fixes - and also the ability to trigger an action based on a link click like you were looking for.

To use this feature, just set `isLinkAction` to `true` on your `menuOption` and register for the event `vnb-item-clicked`. Then, in that handler check the passed `text` value which is the `text` value of your `menuOption`. 

All links will `emit` this event - but the `isLinkAction` will suppress the actual link, so you're not wrestling with an attempted page navigation.

Check out the example to see it working. Thanks, and I hope it helps answer your question.

**Comment by johndatserakis** [comment]
I'll close this for now - let me know how it goes!
