### ISSUE TITLE
@vnb-item-clicked and text of item

### ISSUE THREAD

**Issue by itelmenko** [johndatserakis/vue-navigation-bar#30]
Good package! Thanks for your work!

Sorry, I am not sure it is good idea use text to determine which menu item was pressed.

```
methods: {
    vnbItemClicked(text) {
      if (text === "About") {
        console.log("'About' was selected.");
        const element = document.getElementById("footer");
        element.scrollIntoView({
          behavior: "smooth"
        });
      }
    }
  }
```

It have to be some ID or NAME, but not text.

Please, could you add something like this as parameter for event handler.
But it will be better to have an option to attache handler for item.

**Comment by johndatserakis** [comment]
Hey there, thanks for checking out `vue-navigation-bar`.

While I agree with you that relying on potentially non-unique string is not the best way to identify an item, in this case, we are dealing with specific `menuOptionsLeft` or `menuOptionsRight` items, so we _do_ know the specific structure.

These items are specific to this use-case, and must include a `text` value to show up in the dropdown. In this way, I think it's ok to rely on `text` here.

You bring up a good point though, that I should perhaps add `id` as an optional parameter to `menuOptionsLeft/menuOptionsRight` items to better tie in to a dev's existing data schema.

I will see if I can fit this in when I do an update pass on the library. Thank you for your comment.
