### ISSUE TITLE
Setup for nuxt 3.

### ISSUE THREAD

**Issue by ricky11** [johndatserakis/vue-navigation-bar#33]
Would it be possible to use with nuxt 3?

I created a plugins folder and a fie called vue-nav.js

```
import Vue from 'vue'
import navBar from 'vue-navigation-bar'

Vue.component('navBar', navBar)
```

This should auto register the component without me adding it to nuxt.config.

but in the template when i add nav-bar it doesn't seem to work.

**Comment by johndatserakis** [comment]
Hmm sorry I'm really not sure - I've never used Nuxt in the past.

**Comment by SomethingNew71** [comment]
@ricky11 You need to adjust the way you are defining the plugin. This will solve it. Its not an issue with `vue-navigation-bar`

```ts
// @ts-ignore
import VueNavigationBar from 'vue-navigation-bar';
import { defineNuxtPlugin } from '#app';
import 'vue-navigation-bar/dist/vue-navigation-bar.css';

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component('NavBar', VueNavigationBar);
});
```

**Comment by johndatserakis** [comment]
Thank you, Cole. Closing as answered.
