### ISSUE TITLE
Example is not working correctly on Vue2

### ISSUE THREAD

**Issue by Morphlng** [johndatserakis/vue-navigation-bar#35]
Hello! I'm trying to use vue-navigation-bar as a component in my Vue2 project. I've installed through `npm install vue-navigation-bar@4.1.0` and tried the example code. However, the result is not what I expected:

![example](https://user-images.githubusercontent.com/50166287/200023150-8be2ad65-f004-49b8-af09-2c40055cd56f.png)

Why is that happening? I've noticed that there are some `...` in the example code, is there something else I have to add?

**Comment by johndatserakis** [comment]
Have you added the css `import 'vue-navigation-bar/dist/vue-navigation-bar.css';`? That may be it.

**Comment by Morphlng** [comment]
> Have you added the css `import 'vue-navigation-bar/dist/vue-navigation-bar.css';`? That may be it.

Thank you! This does help.
