### ISSUE TITLE
so many menu items

### ISSUE THREAD

**Issue by liuhaozhi** [johndatserakis/vue-navigation-bar#41]
Love your package. Nice menu. There is a small problem for feedback, that is, when there are more menu items, it will be extended until hidden, and the display is not ideal, do you understand what I mean?
![xx](https://github.com/johndatserakis/vue-navigation-bar/assets/27815483/9c3489ce-ad7d-4b10-aa2d-7008d8b33871)

**Comment by johndatserakis** [comment]
Hi there, yes I see. I think in this case, that many menu items is not usually used, as at that point you would put some items within submenus. But, if you need to have that many items, I would simply overwrite the CSS with something like `overflow: auto` or `flex-wrap: wrap` and take it from there. But again, you may need to reconsider that many items.
