### ISSUE TITLE
can set subMenuOptions in subMenuOptions?

### ISSUE THREAD

**Issue by lizhi2013** [johndatserakis/vue-navigation-bar#5]
in my project,need to add more levels in my project

**Comment by johndatserakis** [comment]
Hey there! I think this is a great suggestion! The only problem is the implementation is definitely going to be a bit complicated to execute. For right now, I would say to just add the items at the root level.

Going forward - let's see if someone wants to take a stab at it. Unfortunately, I think this may be just out of scope for what I can handle at the moment. Thanks!
