### ISSUE TITLE
How to use vue navigation bar in Nuxt App

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [johndatserakis/vue-navigation-bar#6]

**Comment by sholtrop** [comment]
You can use almost any Vue component in Nuxt in this way.
1) In the `plugins` directory, make a file called `vueNavbar.js` with:
```javascript
import Vue from 'vue'
import navBar from 'vue-navigation-bar'

Vue.component('navBar', navBar)
```
This registers the component globally, as 'navBar' (accessible as `<nav-bar>` in `<template>`s).

2) Now you have to register the plugin. In `nuxt.config.js`:
```javascript
plugins: [
  { src: '~/plugins/vueNavbar', mode: 'client' },
  // other plugins...
],
```
3) You can now access it in any Vue component of your Nuxt app:
```vue
<template>
  <nav-bar :options="..."/>
</template>
```

**Comment by johndatserakis** [comment]
Thank you @sholtrop. Closing for now.

**Comment by ricky11** [comment]
How about with nuxt 3?
