### ISSUE TITLE
Need named routes. Path returns relative urls

### ISSUE THREAD

**Issue by mbscholars** [johndatserakis/vue-navigation-bar#7]
Can't named route be added instead of path? Vue router always returns the path relative to the current url. 

` .....
                {
                  type: 'link',
                  text: 'Centers',
                  **path: "{name: 'shops'}"**
                },`

**Comment by johndatserakis** [comment]
Yea I think that's a good idea. The link handling needs to be worked on for sure. I'll get to it as soon as I can.

**Comment by johndatserakis** [comment]
Ok I'm going to being working on this shortly - I'm thinking we try to support both string paths and a route object where we read the name. I'll update here when complete.

Also note to self - keep in mind the `brandImagePath` option - as that'll need to be handled in a similar way.

**Comment by johndatserakis** [comment]
Ok awesome - I just merged a PR for this - it will be released soon as `v4.0.0`. Going forward, if you have `isUsingVueRouter` set to `true`, you'll need to use an `Object` with a `name` property. Check out the `./example` folder for the usage.

Thank you for the suggestion.
