### ISSUE TITLE
The client-side rendered virtual DOM tree is not matching server-rendered content. 

### ISSUE THREAD

**Issue by matmis** [johndatserakis/vue-navigation-bar#8]
## Problem
I'm having this error in my browser console:
`[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.`

The navbar is visible but clicking links doesn't do anything.

## Extra info
I'm using `"vue-navigation-bar": "^2.0.0"` in a **Nuxt.js** app.

In **nuxt.config.js** I have added:
```js
export default {
  css: [
    'vue-navigation-bar/dist/vue-navigation-bar.css'
  ],
  plugins: [
    { src: '~/plugins/vue-navigation-bar', mode: 'client' }
  ]
}
```

### ~/plugins/vue-navigation-bar.js
```js
import Vue from 'vue'
import VueNavigationBar from 'vue-navigation-bar'
Vue.component('vue-navigation-bar', VueNavigationBar)

```

### Use of component
```vue
<template>
  <div>
    <vue-navigation-bar :options="navbarOptions" />
  </div>
</template>

<script>
  export default {
    data () {
      return {
        navbarOptions: {
          elementId: 'main-navbar',
          isUsingVueRouter: true,
          mobileBreakpoint: 992,
          brandImagePath: './',
          brandImage: require('~/assets/logo.png'),
          brandImageAltText: 'brand-image',
          showBrandImageInMobilePopup: true,
          ariaLabelMainNav: 'Main Navigation',
          tooltipAnimationType: 'shift-away',
          menuOptionsLeft: [
            {
              isLinkAction: true,
              type: 'link',
              text: 'Over ons',
              path: '/overOns'
            }
          ]
        }
      }
    }
  }
</script>
```

**Comment by johndatserakis** [comment]
Hi there, sorry you're having trouble. 

Hmm, I've never experienced this error before in any of my Vue apps, but that may be because I don't use `Nuxt.js` myself.

Is there anyway you could pinpoint *what* element is causing that message? I actually put a lot of work into making the component super semantic, so I'm a little concerned to see this message, and I'd like to fix it.

In my searching I found that someone posted some steps to maybe show what element is causing the issue - https://stackoverflow.com/a/49202327. Maybe that can help find the troubled element.

**Comment by SomethingNew71** [comment]
I have solved this issue, though I am not sure if this is the right way to solve it. 

Wrapping the content in `<client-only></client-only>` helpers from nuxt will resolve the DOM mismatch. So it would look like this:

### Before:
```vue
<nav-bar
  :options="navbarOptions"
  @vnb-item-clicked="vnbItemClicked"
  @vnb-mobile-popup-shown="toggleOverlay"
  @vnb-mobile-popup-hidden="toggleOverlay"
/>
```

### After
```vue
<client-only>
  <nav-bar
    :options="navbarOptions"
    @vnb-item-clicked="vnbItemClicked"
    @vnb-mobile-popup-shown="toggleOverlay"
    @vnb-mobile-popup-hidden="toggleOverlay"
  />
</client-only>
```

**Comment by johndatserakis** [comment]
Thank you @SomethingNew71, that makes sense to me.

@matmis - did you try something like what @SomethingNew71 posted above yet? Sounds like this will solve your problem.

**Comment by johndatserakis** [comment]
Closing for now, thank you.
