### ISSUE TITLE
Arrow Color

### ISSUE THREAD

**Issue by jeffreykthomas** [johndatserakis/vue-navigation-bar#9]
I'm struggling with something that seems like it should be simple, so I apologize if I'm missing something obvious

I've added a background a dark background color to the navigation bar, so now the chevron arrow is almost invisible

I changed the chevron-down.png in the package to be white, but it's not showing up as white in my project. Am I missing something?

**Comment by johndatserakis** [comment]
Hmm, when you say that you changed the `chevron-down.png` how did you do that exactly? It's not a prop option. Maybe that's where the issue lies. I think you bring up a good point though, that perhaps that should be a customizable option. Right now, only the collapse button is customizable.

**Comment by jeffreykthomas** [comment]
Everything is functioning, nothing has changed since I changed the png file in the project. It’s just that the arrows are not visible unless you look closely (same as before any attempt to edit), because they are very close to the same color as the background color we chose. If it was customizable that would be awesome

**Comment by johndatserakis** [comment]
Got it, sure, I'll look into getting this turned into a customizable option that takes an image or svg like `collapseButtonImageOpen ` and `collapseButtonImageClose` already do currently. I'm a little tied up at the moment, but I'll update here when I get that done. Thank you.

**Comment by johndatserakis** [comment]
Closed with https://github.com/johndatserakis/vue-navigation-bar/pull/13 - thank you @SomethingNew71. This will be up in a new release shortly. @jeffreykthomas - in the upcoming release you can use `arrowColor` on a `menuOptions` item to change the chevron color to your liking. Edit - the new release is out `v3.0.0`.
